config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'documents/index'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'sessions#destroy', as: :destroy_user_session
  end

  root 'documents#index'

  resources :documents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: %i[doorkeeper]
end

app/controllers/api/base_controller.rb
# frozen_string_literal: true

require 'rocali/commands/strategies/doorkeeper/authorize_api_request'

module Api
  class BaseController < ActionController::API
    include Rocali

    def authenticate_request
      authorize_api_command = Rocali::Strategies::Doorkeeper::AuthorizeApiRequest.call(request.headers)
      @requester_app = authorize_api_command.result
      render json: {error: "Not authorized. #{authorize_api_command.errors}"}, status: 401 unless authorize_api_command.success?
    end
  end
end

app/controllers/api/documents_controller.rb
module Api
  class DocumentsController < Api::BaseController
    before_action :authenticate_request

    def index
      render json: Document.all.as_json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

  def doorkeeper
    user = User.find_or_create_by!(email: request.env['omniauth.auth'].uid)
    sign_in_and_redirect user
  end

  def failure
    redirect_to '/422.html'
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < ApplicationController
  before_action :set_document, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: :index

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show; end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit; end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def document_params
    params.require(:document).permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def destroy
    cookies.delete '_oauth_server_session'
    reset_session
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.description %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @document.description %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Documents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
    <% if current_user %>
      <%= form_tag(destroy_user_session_path, method: :delete) do %>
        You are logged as <b><%= current_user.email %></b>
        <button type='submit'>logout</button>
      <% end %>
    <% else %>
      <%= form_tag(user_doorkeeper_omniauth_authorize_path, method: 'post') do %>
        Welcome to Devise demo <button type='submit'>Login</button>
      <% end %>
    <% end %>
    <hr>
  </div>
    <%= yield %>
  </body>
</html>